### ISSUE TITLE
Код из примера

### ISSUE THREAD

**Issue by gelo11** [NovikovRoman/fssp#1]
Запускаю код из примера, возвращается 400 ошибка.
error: Client error: `POST https://api-ip.fssprus.ru/api/v1.0/search/group?token=...` resulted in a `400 Bad Request` response:
{"status":"error","code":400,"exception":"queries can not be 0","response":[]}

Может сталкивались?

**Comment by NovikovRoman** [comment]
Было заброшено и забыто ). Спасибо что напомнили. Исправлено https://github.com/NovikovRoman/fssp/releases/tag/v0.2.3

**Comment by gelo11** [comment]
Спасибо. Но я нашел другое решение.
Согласно документации нужно при пост запросах передавать другой хедер
`application/x-www-form-urlencoded`

http://docs.guzzlephp.org/en/stable/quickstart.html#post-form-requests

Это и с костылем токена решает вопрос.

**Comment by NovikovRoman** [comment]
С костылем все решилось. Он не нужен. Теперь все работает как надо.
