### ISSUE TITLE
Не выполняет поиск по всем регионам (region=-1)

### ISSUE THREAD

**Issue by bioklan** [NovikovRoman/fssp#2]
Поиск по физическим лицам по всем регионам (region=-1) возвращает пустой массив. Хотя если выбрать например 77 регион, то данные о задолженностях есть. Может быть ошибка в коде или ФССП закрыла эту возможность?

**Comment by bioklan** [comment]
Как вариант обойти ограничение можно создать групповой запрос на коды с 1 по 99.

**Comment by NovikovRoman** [comment]
Проверил. Действительно перекрыли возможность искать по всем регионам :(.
Есть одна задумка. Мне необходим шрифт который используется в капче. Это шрифт Adler дополненный кириллицей. Может есть у кого?

**Comment by Dilitand** [comment]
Печально... Слать по 100 запросов по каждому клиенту - теряется смысл api... слишком медленно, т.к. сервис блокирует частые запросы (вроде 30 штук одиночных в минуту или 1 групповой).

**Comment by WinterSilence** [comment]
можно выбрать 2я групповыми запросами 50 регионов или вначале отправить первый, а если он не даст результатов - второй

> Максимальное число подзапросов в групповом запросе ­— **50** (если требуется отправить большее число, следует разбивать запрос на несколько).
Максимальное число одиночных запросов в час ­— 100. (Ограничение на одиночные запросы считается, как минус час от текущего времени)
Максимальное число групповых запросов в сутки ­— **5000**.
Срок хранения результатов запроса (промежуток между обращениями к методам /search/ и методу /result) — 24 часа.
