### ISSUE TITLE
Выдает ошибку 429 Too Many Requests

### ISSUE THREAD

**Issue by z7FooN** [NovikovRoman/fssp#5]
Здравствуйте. Скрипт перестал работать полностью. Все исправно работало, но вдруг резко стало выдавать ошибку.

Выдает ошибку:

error: Client error: `GET https://api-ip.fssp.gov.ru/api/v1.0/search/physical?token=(тут токен)®ion=28&firstname=%D0%92%D0%B5%D1%80%D0%B0&lastname=%D0%9C%D0%B8%D1%80%D0%BE%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE&secondname=%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%BD%D0%B0&birthdate=09.04.1970` resulted in a `429 Too Many Requests` response: {"status":"error","code":429,"exception":"\u0412\u044b \u0434\u043e\u0441\u0442\u0438\u0433\u043b\u0438 \u043e\u0433\u04 (truncated...)

Использую скрипт на сайте: https://фссп.онлайн/ (встроил ваш скрипт)

**Comment by NovikovRoman** [comment]
К сожалению сервис ФССП крайне тормозная и падучая штука. Видимо у них на raspberry все крутится.
