### ISSUE TITLE
Теперь дата рождения обязательна?

### ISSUE THREAD

**Issue by Ganesha604** [NovikovRoman/fssp#6]
ФССП стал выдавать ошибку "В поле birthdate должна быть дата после 1900-01-01. "

Теперь обязательно вводить дату рождения или они что-то изменили в запросах? так как в описании системы у них до сих пор указано, что это не обязательный параметр. 

Посмотрите, пожалуйста

**Comment by NovikovRoman** [comment]
Обновлений документации пока не было https://api-ip.fssp.gov.ru/swagger

ps есть подозрение что начинают гайки затягивать с АПИ. Связи с техподдержкой нет. Данные не возвращают. На сайте данные есть, в АПИ нет. Похоже им это не интересно и возможно, со временем, перейдут на что-то другое.

**Comment by j1warren** [comment]
if you do searchGroup() then birthdate can't be null
so in /src/Subject/Physical.php params() you can't pass null 'birthdate'

**Comment by NovikovRoman** [comment]
[новая версия](https://github.com/NovikovRoman/fssp/releases/tag/v1.0.0)

**Comment by j1warren** [comment]
https://github.com/NovikovRoman/fssp/blob/9755aa11c7f7d65425d8c10270122b538b97185c/src/Subject/Physical.php#L60
if birthdate is null don't pass [birthdate] here at all. then it works without it.
