### ISSUE TITLE
Скрипт перестал полностью работать?

### ISSUE THREAD

**Issue by z7FooN** [NovikovRoman/fssp#7]
Скрипт перестал полностью работать?

**Comment by NovikovRoman** [comment]
Ключ у вас действует? Срок действия выданного ключа доступа — 1 год.

**Comment by z7FooN** [comment]
> Ключ у вас действует? Срок действия выданного ключа доступа — 1 год.

Да, все работает.

**Comment by NovikovRoman** [comment]
> > Ключ у вас действует? Срок действия выданного ключа доступа — 1 год.
> 
> Да, все работает.

Работает скрипт или ключ действует?)

**Comment by z7FooN** [comment]
> > > Ключ у вас действует? Срок действия выданного ключа доступа — 1 год.
> > 
> > 
> > Да, все работает.
> 
> Работает скрипт или ключ действует?)

Ключ действует

**Comment by z7FooN** [comment]
Я токен создал месяц назад. Сейчас что-то поменялось?

**Comment by NovikovRoman** [comment]
Ничего не менялось. АПИ у них прежнее. Проверил своим ключом. Все отдает.

**Comment by z7FooN** [comment]
> Ничего не менялось. АПИ у них прежнее. Проверил своим ключом. Все отдает.

Хорошо. Будем тогда еще раз пробовать. Отпишу по ситуации. Спасибо за отклик.

**Comment by NovikovRoman** [comment]
[не вышли ли лимиты запросов?](https://github.com/NovikovRoman/fssp/blob/master/README.md)

**Comment by z7FooN** [comment]
> [не вышли ли лимиты запросов?](https://github.com/NovikovRoman/fssp/blob/master/README.md)

А как их проверить? Более менее сделали, но почему-то через раз сервис работает https://фссп.онлайн/

**Comment by NovikovRoman** [comment]
Неделю назад заметил что не только АПИ тормозит, но и сам сайт. Может их досят? При работе с парсером сайта получал часто 503. Пришлось увеличить задержки, хотя они были и так адекватные.

**Comment by z7FooN** [comment]
> Неделю назад заметил что не только АПИ тормозит, но и сам сайт. Может их досят? При работе с парсером сайта получал часто 503. Пришлось увеличить задержки, хотя они были и так адекватные.

Да, была ошибка 503. Я сейчас увеличил задержку на сайте до 10 секунд. Ладно, будем смотреть по ситуации. Вообще не стабильная эта фигня.

**Comment by NovikovRoman** [comment]
Как и большинство госпроектов)

**Comment by z7FooN** [comment]
> Как и большинство госпроектов)

Опять не работает, не выдает информацию.

**Comment by NovikovRoman** [comment]
К сожалению АПИ у них часто отваливается и не работает должным образом. Проще парсить сразу с сайта.

**Comment by z7FooN** [comment]
> К сожалению АПИ у них часто отваливается и не работает должным образом. Проще парсить сразу с сайта.

Не подскажите, как это сделать? Может за отдельную плату сделать сможете?

**Comment by NovikovRoman** [comment]
> Не подскажите, как это сделать?

отправка формы кодом. Разгадывание капчи сервисом антикапчи или написать своего бота с компьтерным зрением. В ответ получим таблицу с данными. Парсим данные в массив.

> Может за отдельную плату сделать сможете?

У меня просто нет времени на это (

**Comment by z7FooN** [comment]
> > Не подскажите, как это сделать?
> 
> отправка формы кодом. Разгадывание капчи сервисом антикапчи или написать своего бота с компьтерным зрением. В ответ получим таблицу с данными. Парсим данные в массив.
> 
> > Может за отдельную плату сделать сможете?
> 
> У меня просто нет времени на это (

аа вы предлагаете просто спарсить себе базу и выдавать её? Не, мне нужны свежие данные)

**Comment by NovikovRoman** [comment]
я про свежие. Просто бот заполняет форму и "жмет" найти.
Старые записи, если надо обновить, то бот и по ним проходится по таймеру.
