### ISSUE TITLE
Запрос св

### ISSUE THREAD

**Issue by Ganesha604** [NovikovRoman/fssp#9]
Я заметил, что он перестал выдавать информацию, так как появился статус 2 - запрос находится в очереди. 
И присваивает код, по которому якобы можно будет узнать его результат.

Можно ли что-то с этим сделать? Спасибо

![image](https://user-images.githubusercontent.com/75337514/143284458-f719ee02-1f5e-4a61-a1ba-385d6e0cdedd.png)

**Comment by Ganesha604** [comment]
Если задержу вывода ответа сделать 60 сек, то он покажет статус "поле не является датой".
Хотя сделано вроде все как в скрипте
new \DateTime('1987-11-13')
![image](https://user-images.githubusercontent.com/75337514/143286367-03b47ec6-ec43-4548-ab80-7217f5c17740.png)

**Comment by NovikovRoman** [comment]
[Описание интерфейса](https://api-ip.fssp.gov.ru/about) и [справочник АПИ](https://api-ip.fssp.gov.ru/swagger) - здесь описаны все статусы и как с этим работать. После отправки данных вы должны получить taskID для дальнейшего запроса статуса или результатов.

"Срок хранения результатов запроса (промежуток между обращениями к методам /search/ и методу /result) — 24 часа."
